OPENAI_API_KEY = ""
MODEL_SUMMARY = "gpt-5.4-nano"
MODEL_DEEP = "gpt-5.4-mini"

ZOTERO_API_KEY = ""
ZOTERO_USER_ID = ""
ZOTERO_COLLECTION = ""
ZOTERO_LOCAL_DIR = "/path/to/Zotero"

RESEARCH_DIRECTION = ""

TITLE_SCREEN_BIORXIV = 10
TITLE_SCREEN_ARXIV = 10
TITLE_SCREEN_PUBMED = 10

TARGET_JOURNALS = []

TOP_K = 10
FETCH_LOOKBACK_DAYS = 30
RUN_PUBMED = True
